
apiVersion: v1
kind: Service
metadata:
  name: app-two-containers-service
spec:
  type: NodePort
  selector:
    running: runn
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31861
        
